name: Build and Test
on: [push, pull_request]

jobs:
  all:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install dependencies
        run: |
          sudo apt-get -y install xz-utils
          sudo bin/_ bin install https://storage.googleapis.com/shellcheck/shellcheck-latest.linux.x86_64.tar.xz
          gem install rubocop
          npm install -g markdownlint-cli

      - name: Build
        run: |
          rake

      - name: Test Shell
        run: |
          rake test lang=sh

      - name: Test Ruby
        run: |
          rake test lang=rb

      - name: Test Markdown
        run: |
          rake test lang=md
